[variables]
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = [
  "rm -rf node_modules package-lock.json",
  "npm install --include=dev"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
